export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const FETCH_ROBOTS_PIENDING = "FETCH_ROBOTS_PIENDING";
export const FETCH_ROBOTS_SUCCESS = "FETCH_ROBOTS_SUCCEES";
export const FETCH_ROBOTS_FAILD = "FETCH_ROBOTS_FAILD";
